services:
  database:
    image: postgres:17
    container_name: arcadia_database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: arcadia
      POSTGRES_DB: arcadia
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    networks:
      - arcadia_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arcadia_backend
    ports:
      - "8080:8080"
    networks:
      - arcadia_network
    depends_on:
      - database

volumes:
  postgres:

networks:
  arcadia_network:
    driver: bridge